sudo: required
services:
    - docker

before_install:
    - docker build -t thedefede/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true thedefede/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    access_key_id: 
    secret_access_key:
    region: "sa-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-sa-east-1-753611795627"
    bucket_path: "docker-react"
    on:
        branch: master
